name: Latest blog post workflow
on: 
    schedule:
        - cron: '0 * * * *'  # Runs every hour
    workflow_dispatch:
jobs: 
    update-readme-with-blog: 
        name: Update this repo's README with latest blog posts
        runs-on: ubuntu-latest
        steps: 
            - name: Checkout code
              uses: actions/checkout@v3
            - name: Check RSS Feed
              run: |
                curl -s "https://medium.com/feed/@tarimbilal4"  # Fetch the feed to check its content
            - name: Pull in latest blog posts
              uses: gautamkrishnar/blog-post-workflow@master  # Replace with the latest stable version
              with: 
                max_post_count: "4"
                feed_list: "https://medium.com/feed/@tarimbilal4"
